export const SIGNIN_USER = 'SIGNIN_USER';
export const SIGNUP_USER = 'SIGNUP_USER';
export const CLEAR_USER = 'CLEAR_USER';
export const SET_LOADING = 'SET_LOADING';
// export const VERIFY_CNIC = 'VERIFY_CNIC';
// export const CLEAR_ERRORS = 'CLEAR_ERRORS';
// export const GET_ERRORS = 'GET_ERRORS';
// export const GET_EMAIL_ERRORS = 'GET_EMAIL_ERRORS';
// export const GET_PASSWORD_ERRORS = 'GET_PASSWORD_ERRORS';
